#!/bin/bash
assert() {
    expected="$1"
    input="$2"

    ./9cc "$input" > tmp.s
    cc -o tmp tmp.s test/tool/funccalltest.o test/tool/alloctesthelper.o
    ./tmp
    actual="$?"

    if [ "$actual" = "$expected" ]; then
        echo "$input => $actual"
    else
        echo "$input => $expected expected, but got $actual"
        exit 1
    fi
}

assert 0 "test/old/test-aa.c"
assert 42 "test/old/test-ab.c"
assert 21 "test/old/test-ac.c"
assert 41 "test/old/test-ad.c"
assert 47 "test/old/test-ae.c"
assert 15 "test/old/test-af.c"
assert 4 "test/old/test-ag.c"
assert 10 "test/old/test-ah.c"
assert 2 "test/old/test-ai.c"
assert 1 "test/old/test-aj.c"
assert 0 "test/old/test-ak.c"
assert 1 "test/old/test-al.c"
assert 0 "test/old/test-am.c"
assert 1 "test/old/test-an.c"
assert 0 "test/old/test-ao.c"
assert 16 "test/old/test-ap.c"
assert 44 "test/old/test-aq.c"
assert 25 "test/old/test-ar.c"
assert 44 "test/old/test-as.c"
assert 40 "test/old/test-at.c"
assert 15 "test/old/test-au.c"
assert 15 "test/old/test-av.c"
assert 10 "test/old/test-aw.c"
assert 15 "test/old/test-ax.c"
assert 15 "test/old/test-ay.c"
assert 15 "test/old/test-az.c"
assert 10 "test/old/test-ba.c"
assert 20 "test/old/test-bb.c"
assert 0 "test/old/test-bc.c"
assert 13 "test/old/test-bd.c"
assert 25 "test/old/test-be.c"
assert 36 "test/old/test-bf.c"
assert 70 "test/old/test-bg.c"
assert 76 "test/old/test-bh.c"
assert 81 "test/old/test-bi.c"
assert 85 "test/old/test-bj.c"
assert 1 "test/old/test-bk.c"
assert 3 "test/old/test-bl.c"
assert 6 "test/old/test-bm.c"
assert 10 "test/old/test-bn.c"
assert 15 "test/old/test-bo.c"
assert 21 "test/old/test-bp.c"
assert 28 "test/old/test-bq.c"
assert 36 "test/old/test-br.c"
assert 45 "test/old/test-bs.c"
assert 55 "test/old/test-bt.c"
assert 6 "test/old/test-bu.c"
# assert 110 "test/old/test-bv.c"
assert 1 "test/old/test-bw.c"
assert 2 "test/old/test-bx.c"
assert 3 "test/old/test-by.c"
assert 1 "test/old/test-bz.c"
assert 2 "test/old/test-ca.c"
assert 4 "test/old/test-cb.c"
assert 8 "test/old/test-cc.c"
assert 1 "test/old/test-cd.c"
assert 2 "test/old/test-ce.c"
assert 4 "test/old/test-cf.c"
assert 8 "test/old/test-cg.c"
assert 1 "test/old/test-ch.c"
assert 2 "test/old/test-ci.c"
assert 4 "test/old/test-cj.c"
assert 8 "test/old/test-ck.c"
assert 1 "test/old/test-cl.c"
assert 2 "test/old/test-cm.c"
assert 4 "test/old/test-cn.c"
assert 8 "test/old/test-co.c"
assert 4 "test/old/test-cp.c"
assert 8 "test/old/test-cq.c"
assert 0 "test/old/test-cr.c"
assert 64 "test/old/test-cs.c"
assert 3 "test/old/test-ct.c"
assert 1 "test/old/test-cu.c"
assert 2 "test/old/test-cv.c"
assert 3 "test/old/test-cw.c"
assert 3 "test/old/test-cx.c"
assert 3 "test/old/test-cy.c"
assert 3 "test/old/test-cz.c"
assert 1 "test/old/test-da.c"
assert 3 "test/old/test-db.c"
assert 3 "test/old/test-dc.c"
assert 1 "test/old/test-dd.c"
assert 1 "test/old/test-de.c"
assert 5 "test/old/test-df.c"
assert 3 "test/old/test-dg.c"
assert 97 "test/old/test-dh.c"
assert 98 "test/old/test-di.c"
assert 99 "test/old/test-dj.c"
assert 100 "test/old/test-dk.c"
assert 101 "test/old/test-dl.c"
assert 102 "test/old/test-dm.c"
assert 102 "test/old/test-dn.c"

echo OK

